name: Build EXE on action branch

on:
  push:
    branches: [ action ] 
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --noconfirm --clean --console --add-data "BaseImages;BaseImages" --add-data "font.ttf;." --add-data "config.py;." main.py

    - name: Package as ZIP
      run: |
        $branch = "${{ github.ref_name }}"
        $sha = "${{ github.sha }}"
        $zipName = "AnAn_Sketchbook_${branch}_${sha:0:7}.zip"
        Compress-Archive -Path "dist\main.exe", "BaseImages", "font.ttf", "config.py" -DestinationPath $zipName
        echo "ZIP_NAME=$zipName" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Sketchbook-Build-${{ github.run_number }}
        path: ${{ env.ZIP_NAME }}